sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vanerod/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vanerod/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'Dockerenv'
  env: 'Dockerenv-env'
  bucket_name: 'elasticbeanstalk-us-east-1-441813618543'
  bucket_path: 'Dockerenv'
  on:
    branch: master
  access_key_id: $AWS-docker
  secret_access_key: $AWS-docker-secret
